version: '3'
services:
    postgresql:
        image: postgres:13.3-alpine
        container_name: postgresql
        volumes: 
            - ./datadir:/var/lib/postgresql/data
            - ./db:/docker-entrypoint-initdb.d # 初始化sql脚本，无需初始化可注释
        restart: always
        environment: 
            POSTGRES_PASSWORD: abc123
            POSTGRES_DB: test_db
        networks:
            - "db_network"
        expose: 
            - "5432"
        ports: 
            - "5432:5432"
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: abc123
        expose:
            - '27017'
        ports:
            - '27017:27017'
        networks:
            - "db_network"
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        expose:
            - '8081'
        ports:
            - 8081:8081
        networks:
            - "db_network"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: abc123
            ME_CONFIG_MONGODB_SERVER: mongo
            # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
networks:
    db_network:
