version: '3'
services:
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: abc123
        expose:
            - '27017'
        ports:
            - '27017:27017'
        networks:
            - "mongo_network"
        # command: mongo --config /etc/mongo/mongod.conf

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        expose:
            - '8081'
        ports:
            - 8081:8081
        networks:
            - "mongo_network"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: abc123
            ME_CONFIG_MONGODB_SERVER: mongo
            # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
networks:
    mongo_network:
