version: '3'
services:
    redis:
        image: redis:6-alpine
        container_name: redis
        networks:
            - "redis_network"
        expose:
            - '6379'
        ports:
            - "6379:6379"
        volumes:
            - ./conf/redis.conf:/etc/redis/redis.conf
            - ./data:/data
        command: redis-server /etc/redis/redis.conf

networks:
    redis_network:
